# NumPy [8] Álgebra lineal

In [8]:
import numpy as np
m = np.array([[1,2,3], [-2,0,1]])
print(m)

[[ 1  2  3]
 [-2  0  1]]


In [9]:
b = np.array([[1],[2],[3]])
print(b)

[[1]
 [2]
 [3]]


## Transposición matricial

In [10]:
a = np.transpose(b)           # cambiamos filas por columnas
print(a)

[[1 2 3]]


In [11]:
np.transpose(m)

array([[ 1, -2],
       [ 2,  0],
       [ 3,  1]])

In [13]:
print(np.transpose(a))

[[1]
 [2]
 [3]]


#### Comprobación
Es necesario usar dobles corchetes.

In [14]:
print(np.transpose([[1, 2, 3]]))

[[1]
 [2]
 [3]]


## Resolución de sistemas lineales
$$Ax=b$$
Nuestro objetivo es calcular $x$.

$$A=
\begin{pmatrix}
1 & -3 &  2\\
5 &  6 & -1\\
4 & -1 &  3
\end{pmatrix}$$ 

$$b=
\begin{pmatrix}
-3 \\
13 \\
8 
\end{pmatrix}$$

Solución:
$$x=A^{-1}b$$

In [15]:
A = np.array([[1,-3,2],[5,6,-1],[4,-1,3]])
print(A)

array([[ 1, -3,  2],
       [ 5,  6, -1],
       [ 4, -1,  3]])

In [16]:
b = np.array([[-3],[13],[8]])
print(b)

[[-3]
 [13]
 [ 8]]


In [17]:
x = np.linalg.solve(A,b)

In [19]:
print(x)

[[-2.]
 [ 5.]
 [ 7.]]


#### Comprobación
La función allclose nos permite comprobar que los valores aúnque no sean exactamente iguales, si son muy cercanos.

In [20]:
np.allclose(np.dot(A,x),b)

True

In [22]:
np.dot(A,x)

array([[-3.],
       [13.],
       [ 8.]])

In [23]:
b

array([[-3],
       [13],
       [ 8]])

In [25]:
np.dot(A,x)-b

array([[-3.55271368e-15],
       [ 0.00000000e+00],
       [ 3.55271368e-15]])

### Otra forma de cambiar las dimensiones de un vector
En la práctica equivale a transponer el vector.

In [37]:
c = np.array([1,2,3])
print(c)

[1 2 3]


In [38]:
c.shape=(3,1)
c

array([[1],
       [2],
       [3]])

In [39]:
c.shape=(1,3)
c

array([[1, 2, 3]])