# Paquetes más usados

Contienen código que amplian las funcionalidades de Python.  
Los paquetes están contenidos en una carpeta con código .py  
Tienen una estructura diseñada para poder usar funciones y clases  
\_\_init\_\_.py

## En Anaconda  
Si estamos usando Anaconda no necesitamos instalar paquetes porque ya los trae incluidos. En caso contrario, es posible que tengas que instalarlo con el instalador de paquetes de Python **pip**.

## Cómo importar un paqute  
NumPy: Acrónimo de  Numerical Python

Simplemente tecleando lo siguiente estaríamos importando el paquete numpy con todas sus funciones.

In [ ]:
import numpy

In [ ]:
# ejemplo, usando la función arange del paquete
numpy.arange(10)

### Cómo importar un paquete con alias

In [ ]:
import numpy as np         # es el método recomendado
np.arange(10)              # ya que al ver np.arange ya sabemos que se trata de la función arange del paquete numpy

### Cómo importar una función concreta del paquete

In [ ]:
from numpy import arange
arange(10)

**Ejemplo**  

In [1]:
import numpy as np
x = np.arange(1,4)
print('x=',x)
print('e^x =',np.exp(x))
print("Type de x:",type(x))

x= [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
Type de x: <class 'numpy.ndarray'>


# Diferencia entre funciones y métodos

- Función: conjunto de instrucciones que proporcionan un return
- Método: conjunto de instrucciones que van a trabajar sobre un objeto

In [ ]:
# Calculemos la media de x
print(np.mean(x))        # usando una función   a la función mean le pasamos el argumento x
print(x.mean())          # usando un método     x es un objeto al que se aplica el método mean()

In [ ]:
# Vamos a transformar las dimensiones de un array
import numpy as np
y = np.arange(10,100,10)
print(y)

In [ ]:
np.reshape(y, (3,3))     # usando una función, primero escribimos la función y luego le pasamos los parámetros

In [ ]:
y.reshape(3,3)     # usando un método, el método reshape se aplica sobre el objeto, solo le pasamos las coordenadas

## Encademamiento de métodos (method chaining)  
También se puede usar el encadenamiento de métodos.  
objeto.método1().método2().método3()

In [ ]:
import numpy as np
x = np.arange(1,5)
print('x=',x)
y = np.exp(x)
print('y=',y)
print(np.round(y,2))
print(y.round(2))
matriz = [x,y]
print("matriz=", matriz)

In [ ]:
from numpy.random import randint
values1 = randint(0, 10, 20)
values2 = randint(0, 10, 20)
print(values1)
print(values2)

## Redondear con ```round```

In [ ]:
import numpy as np
valores = np.random.standard_normal(6)  # array de 6 números aleatorios Normal standard
print(valores)

In [ ]:
redondeado1 = np.round(valores)                                            # usando round como función
redondeado2 = np.round(valores,2)
print ("Array redondeado a 0 decimales : ", redondeado1)
print ("Array redondeado a 2 decimales : ", redondeado2)

In [ ]:
print ("Array redondeado a 3 decimales : ", valores.round(3))              # usando round como método

In [ ]:
# usando el argumento optativo out en numpy.round(a, decimals=0, out=None)
x = np.arange(6, dtype=np.float64)  # inicializamos x como un ndarray de 6 posiciones para datos float
valores.round(4,x)                  # x es es argumento optativo: out

## Permutamos x e y con swapaxes(axis1, axis2)

In [7]:
from numpy import swapaxes,arange,reshape 
a = arange(10).reshape(5,2)  # creamos un ndarray de 5 fila y 2 columnas

print(f'La matriz original: \n{a}') 
print()

# permutamos los valores entre el eje 0 y el eje 1 
print('La matriz con los ejes permutados usando swapaxes como función:') 
print(swapaxes(a, 1, 0))     # primero ponemos el eje 1 y luego el eje 0, swapaxes actúa como función
print()

print('Partimos nuevamente de la matriz original:')
print(a)
print()

print('La matriz con los ejes permutados usando swapaxes como método:')
print(a.swapaxes(1, 0))                                                 # swapaxes actúa como método

La matriz original: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

La matriz con los ejes permutados usando swapaxes como función:
[[0 2 4 6 8]
 [1 3 5 7 9]]

Partimos nuevamente de la matriz original:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

La matriz con los ejes permutados usando swapaxes como método:
[[0 2 4 6 8]
 [1 3 5 7 9]]


# Los paquetes más usados  
## Procesamiento de datos  
- **Numpy**
- SciPy
- **Pandas**
- PySpark
## Visualización  
- **Matplotlib**
- Plotly
- Bokeh
- Seaborn
## Modelos ML-AI  
- TensorFlow
- Keras
- PYTORCH
- scikit learn
## Minería de datos y de textos  
- Flask (servidor Web)
- Scrapy
- BeatifulSoup
