# Paquetes más usados

Contienen código que amplian las funcionalidades de Python.  
Los paquetes están contenidos en una carpeta con código .py  
Tienen una estructura diseñada para poder usar funciones y clases  
\_\_init\_\_.py

## En Anaconda  
Si estamos usando Anaconda no necesitamos instalar paquetes porque ya los trae incluidos. En caso contrario, es posible que tengas que instalarlo con el instalador de paquetes de Python pip.

## Cómo importar un paqute  
NumPy: Acrónimo de  Numerical Python

Simplemente tecleando lo siguiente estaríamos importando el paquete numpy con todas sus funciones.

In [1]:
import numpy

In [2]:
# ejemplo, usando la función arange del paquete
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Cómo importar un paquete con alias

In [3]:
import numpy as np               # es el método recomendado
np.arange(10)                    # ya que al ver np.arange ya sabemos que se trata de la función arange del paquete numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Cómo importar una función concreta del paquete

In [5]:
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ejemplo**  

In [11]:
import numpy as np
x=np.arange(1,4)
print('x=',x)
print('e^x =',np.exp(x))
print("Type de x:",type(x))

x= [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
Type de x: <class 'numpy.ndarray'>


# Diferencia entre funciones y métodos

- Función: conjunto de instrucciones que proporcionan un return
- Método: conjunto de instrucciones que van a trabajar sobre un objeto

In [12]:
# Calculemos la media de x
print(np.mean(x))        # usando una función   a la función mean le pasamos el argumento x
print(x.mean())          # usando un método     x es un objeto al que se aplica el método mean()

2.0
2.0


In [14]:
# Vamos a transformar las dimensiones de un array
import numpy as np
y=np.arange(10,100,10)
print(y)

[10 20 30 40 50 60 70 80 90]


In [15]:
np.reshape(y, (3,3))     # usando una función   primero escribimos la función y luego le pasamos los parámetros

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
y.reshape(3,3)           # usando un método     el método reshape se aplica sobre el objeto y, donde solo le pasamos las coordenadas

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Encademamiento de métodos (method chaining)  
También se puede usar el encadenamiento de métodos.  
objeto.método1().método2().método3()

In [25]:
import numpy as np
x=np.arange(1,5)
print('x=',x)
y=np.exp(x)
print('y=',y)
print(np.round(y,2))
print(y.round(2))
print(y.round(2))
matriz=[x,y]
print("matriz=",matriz)

x= [1 2 3 4]
y= [ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 2.72  7.39 20.09 54.6 ]
[ 2.72  7.39 20.09 54.6 ]
[ 2.72  7.39 20.09 54.6 ]
matriz= [array([1, 2, 3, 4]), array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])]


In [8]:
from numpy.random import randint
values1 = randint(0, 10, 20)
values2 = randint(0, 10, 20)
print(values1)
print(values2)

[5 4 6 4 1 0 7 1 6 5 1 1 7 0 3 1 7 6 7 9]


array([9, 1, 4, 2, 0, 4, 5, 6, 4, 3, 0, 8, 1, 9, 6, 8, 0, 1, 4, 9])

redondeamos con round([decimals, out]) y permutamos x e y con swapaxes(axis1, axis2)

# Los paquetes más usados  
## Procesamiento de datos  
- **Numpy**
- SciPy
- **Pandas**
- PySpark
## Visualización  
- **Matplotlib**
- Plotly
- Bokeh
- Seaborn
## Modelos ML-AI  
- TensorFlow
- Keras
- PYTORCH
- scikit learn
## Minería de datos y de textos  
- Flask
- Scrapy
- BeatifulSoup
