# NumPy [1]  
Paquete para cómputo científico: NumPy o Numeric Python.
Permite:
- trabajar con vectores o matrices denominadas **ndarray** (similar a una lista pero mejor) ndarray significa n-dimensional array
- hacer cálculos matemáticos y estadísticos

NumPy ya está instalado en Anaconda, pero si trabaja fuera de este entorno es posible que necesite intalarlo así:  
pip3 install numpy    # pip3 es la versión del instalador pip para Python 3

## Diferencia entre lista y dnarray 
* Las listas pueden estar compuestas de datos de tipos diferentes, por el contrario los ndarrays deben ser de uniformes 
* Los ndarrays son más adecuados para trabajar como en álgebra, son más flexibles

In [6]:
import numpy as np           # importamos la librería NumPy como np
vector = np.array([2,4,6])   # ndarray
lista = [1,3,5]              # lista
print(vector)                # pares
print(lista)                 # impares

[2 4 6]
[1, 3, 5]


In [2]:
                             # añadiendo un valor a una lista con append
lista.append(7)
print(lista)
                             # añadiendo un nuevo elemento a un array --> ¡Sorpresa!
print(vector+np.array(8))    # no añade 8 al array de los pares, lo que hace es sumarlo a todos
vector+np.array(8)           # si no ponemos print aparece como: array([10, 12, 14])

[1, 3, 5, 7]
[10 12 14]


array([10, 12, 14])

In [3]:
np.append(vector,8)          # para hacer un append con un ndarray

array([2, 4, 6, 8])

In [4]:
                             # sumando listas
a = [1,2,3]
b = [4,5,6]
print(a+b)                   # la suma de listas es una concatenación

                             # sumando arrays
x = np.array(a)
y = np.array(b)
print(x+y)                   # la suma de arrays si suma los valores como en álgebra

[1, 2, 3, 4, 5, 6]
[5 7 9]


## ¿Por qué un ndarray es más flexible que una lista?
Supongamos que tenemos dos listas una con la altura de 11 personas y otra con su peso.  
Deseamos poder calcular el IMC (Índice de Masa Corporal) ratio que es peso / altura\*\*2.

In [ ]:
altura=[1.6,1.71,1.82,1.52,1.59,1.95,1.71,1.75,1.66,1.56,1.99]
peso=[48.8,57.4,87.2,39.5,51.5,97.4,55.2,52.2,52.7,50.6,76.1]
type(peso)

Veamos que al calcular el IMC con listas obtenemos un error.

In [ ]:
#IMC = peso / altura**2        # TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Vamos ahora a ver que los ndarray son mucho más flexibles.

Primero los creamos.

In [ ]:
import numpy as np             # Importamos la librería NumPy
np_peso=np.array(peso)         # creamos el array para el peso
np_altura=np.array(altura)     # creamos el array para la altura
print(type(np_peso))           # veamos el tipo de un ndarray
np_altura                      # mostramos el array para la altura, así se ve un ndarray

Finalmente calculamos el IMC de forma sencilla y elegante.

In [ ]:
IMC = np_peso / np_altura**2
IMC

In [ ]:
# Funciona el referirnos a los elementos del vector por el índice
IMC[2]                  # muestra el tercer elemento del array

In [ ]:
IMC > 23                 # obtenemos un vector con verdaderos y falsos

In [ ]:
# muestra los elementos con sobrepeso
IMC[IMC>23]              # muestra solo los valores de IMC que son True en el vector

Vamos a realizar un gráfico con la nube de puntos entre peso (x) y altura (y).  
También necesitamos importar la librería matplotlib para la representación gráfica.

In [ ]:
import matplotlib.pyplot as plt
x=np_peso
y=np_altura
plt.scatter(x,y)                # scatter para nube de puntos y plot para lineas
plt.xlabel("Peso (Kg)")
plt.ylabel("Altura (m)")
#plt.show()                     # muestra el gráfico
plt.grid()                      # muestra el gráfico con rejilla

## Creamos un ndarray

In [9]:
import numpy as np
numeros_primos=[2,3,5,7,11,13,17,19,23,29]  # esto es una lista normal
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

### Caso 1  
Creando un array en numpy a partir de una lista.

In [10]:
array_primos=np.array(numeros_primos)
array_primos                               # se parece a una lista normal pero es un objeto llamado ndarray

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

### Caso 2  
Inicializando un array con ceros en numpy.

In [11]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Caso 3  
Crear arrays con números.

In [12]:
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Caso 4  
Creando arrays de series de números con un cierto paso.

In [13]:
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Caso 5  
Haciendo un reshape para dos dimensiones

In [14]:
array_pares.reshape(2,5)      # obtenemos una matriz de 2 filas y 5 columnas

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### Caso 6  
La forma habitual de obtener una matriz de dos dimensiones.  
Partimos de una lista de listas que vamos a llamar lista2d.  
Tiene 3 filas y 4 columnas. Es de dimensión 3×4.

In [21]:
lista2d = [[11,12,13,14], [21,22,23,24], [31,32,33,34]]
lista2d

[[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]

Convertimos la lista de listas en un ndarray.

In [22]:
matriz2d = np.array(lista2d) # al ndarray le llamamos matriz2d
matriz2d

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

### Caso 7  
Veamos otro caso con reshape de dimensión 3×5.

In [25]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Operar con arrays

### Operaciones aritméticas

In [ ]:
array_impares=array_pares+1   # suma 1 a todos los elementos y lo convierte en un array de impares
array_impares

In [ ]:
array_impares*10  # multiplicar

In [ ]:
array_impares - array_pares  # restar arrays

In [ ]:
#array_impares/array_pares # dividir arrays    da error ya que dividen entre cero

### Estadística

In [ ]:
array_primos.sum()        # suma

In [ ]:
array_primos.mean()        # media

In [ ]:
array_primos.var()        # varianza

### Ordenación de arrays

In [ ]:
# Creamos la serie de Fibonacci
fibo=[0,1]
for i in range (11):
    fibo.append(fibo[-1]+fibo[-2])
print(fibo)

In [ ]:
# Convertimos la lista en un ndarray
fibonacci=np.array(fibo)
fibonacci

#### Desordenamos

In [ ]:
# desordenamos el array
np.random.shuffle(fibonacci)   # permite desordenar un array
fibonacci

#### Ordenamos

In [ ]:
# ordenar un array
np.sort(fibonacci)          # ordena el vector pero no queda asignado al array fibonacci

In [ ]:
fibonacci # comprobamos que no queda asignado el vector ordenado a la variable fibonacci

In [ ]:
ordenado=np.sort(fibonacci)   # asignamos el array a la variable ordenado
ordenado

#### Reverso

In [ ]:
inverso=ordenado[::-1]
inverso

In [ ]:
inverso.sort() # si ordenamos el array inverso quedará ordenado de menor a mayor
inverso

In [ ]:
inverso==np.array(fibo)     # una comprobación