<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/calisto3_0020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Paquetes más usados

Contienen código que amplían las funcionalidades de Python.  
Los paquetes están contenidos en una carpeta con código .py  
Tienen una estructura diseñada para poder usar funciones y clases  
\_\_init\_\_.py

## En Anaconda  
* Si estamos usando Anaconda, habitualmente no necesitamos instalar paquetes ya  que la mayoría los trae incluidos.
* En caso contrario, es posible que tengas que instalarlo con el instalador de paquetes que para Anaconda es **conda**.

## En Google Colab
* También trae incluidas una gran cantidad de librerías.
* Pero alguna no las incluye y es necesario que se tengan que instalar con el instalador de paquetes de Python **pip**.
* Si estás usando **pip** desde Google Colab, en ocasiones es necesario poner una admiración delante.
 - Ejemplo

 ```bash
 !pip install <paquete>
 ```

## Cómo importar un paquete  
NumPy: Acrónimo de  Numerical Python

Simplemente tecleando lo siguiente estaríamos importando el paquete numpy con todas sus funciones.

In [ ]:
import numpy

In [ ]:
# ejemplo, usando la función arange del paquete
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Cómo importar un paquete con alias

In [ ]:
import numpy as np         # es el método recomendado
np.arange(10)              # ya que al ver np.arange ya sabemos que se trata de la función arange del paquete numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Cómo importar una función concreta del paquete

In [ ]:
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ejemplo**  

In [ ]:
import numpy as np
x = np.arange(1,4)
print('x =', x)
print('e^x =', np.exp(x))
print("Type de x:", type(x))

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
Type de x: <class 'numpy.ndarray'>


# Diferencia entre funciones y métodos

- Función: conjunto de instrucciones que proporcionan un return
- Método: conjunto de instrucciones que van a trabajar sobre un objeto

In [ ]:
# Calculemos la media de x
print(np.mean(x))        # usando una función   a la función mean le pasamos el argumento x
print(x.mean())          # usando un método     x es un objeto al que se aplica el método mean()

2.0
2.0


In [ ]:
# Vamos a transformar las dimensiones de un array
import numpy as np
y = np.arange(10, 100, 10)
print(y)

[10 20 30 40 50 60 70 80 90]


In [ ]:
np.reshape(y, (3, 3))  # usando una función, primero escribimos la función y luego le pasamos los parámetros

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
y.reshape(3, 3)  # usando un método, el método reshape se aplica sobre el objeto, solo le pasamos las coordenadas

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Encadenamiento de métodos (method chaining)  
También se puede usar el encadenamiento de métodos.  
objeto.método1().método2().método3()

In [ ]:
import numpy as np
x = np.arange(1, 5)
print('x =', x)
y = np.exp(x)
print('y =',y)
print(np.round(y, 2))
print(y.round(2))
matriz = [x, y]
print("matriz =", matriz)

x = [1 2 3 4]
y = [ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 2.72  7.39 20.09 54.6 ]
[ 2.72  7.39 20.09 54.6 ]
matriz = [array([1, 2, 3, 4]), array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])]


In [ ]:
from numpy.random import randint
values1 = randint(0, 10, 20)
values2 = randint(0, 10, 20)
print(values1)
print(values2)

[5 2 3 9 8 6 4 3 9 1 5 4 8 0 0 7 5 8 3 8]
[9 9 1 9 5 9 9 1 4 3 1 1 3 6 1 8 7 5 4 1]


## Redondear con ```round```

In [ ]:
import numpy as np
valores = np.random.standard_normal(6)  # array de 6 números aleatorios Normal standard
print(valores)

[-1.44880966  0.10668615  2.02415308  0.65956746  1.31120024  0.58762406]


In [ ]:
redondeado1 = np.round(valores)                                            # usando round como función
redondeado2 = np.round(valores,2)
print ("Array redondeado a 0 decimales : ", redondeado1)
print ("Array redondeado a 2 decimales : ", redondeado2)

Array redondeado a 0 decimales :  [-1.  0.  2.  1.  1.  1.]
Array redondeado a 2 decimales :  [-1.45  0.11  2.02  0.66  1.31  0.59]


In [ ]:
print ("Array redondeado a 3 decimales : ", valores.round(3))              # usando round como método

Array redondeado a 3 decimales :  [-1.449  0.107  2.024  0.66   1.311  0.588]


In [ ]:
# usando el argumento optativo out en numpy.round(a, decimals=0, out=None)
x = np.arange(6, dtype=np.float64)  # inicializamos x como un ndarray de 6 posiciones para datos float
valores.round(4, x)                  # x es un argumento optativo: out

array([-1.4488,  0.1067,  2.0242,  0.6596,  1.3112,  0.5876])

## Permutamos x e y con swapaxes(axis1, axis2)

In [ ]:
from numpy import swapaxes,arange,reshape 
a = arange(10).reshape(5, 2)  # creamos un ndarray de 5 fila y 2 columnas

print(f'La matriz original: \n{a}') 
print()

# permutamos los valores entre el eje 0 y el eje 1 
print('La matriz con los ejes permutados usando swapaxes como función:') 
print(swapaxes(a, 1, 0))     # primero ponemos el eje 1 y luego el eje 0, swapaxes actúa como función
print()

print('Partimos nuevamente de la matriz original:')
print(a)
print()

print('La matriz con los ejes permutados usando swapaxes como método:')
print(a.swapaxes(1, 0))                                                 # swapaxes actúa como método

La matriz original: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

La matriz con los ejes permutados usando swapaxes como función:
[[0 2 4 6 8]
 [1 3 5 7 9]]

Partimos nuevamente de la matriz original:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

La matriz con los ejes permutados usando swapaxes como método:
[[0 2 4 6 8]
 [1 3 5 7 9]]


# Los paquetes más usados  
## Procesamiento de datos  
- **Numpy**
- SciPy
- **Pandas**
- PySpark
## Visualización  
- **Matplotlib**
- Plotly
- Bokeh
- Seaborn (gráficos)
## Modelos ML-AI  
- TensorFlow
- Keras (deep learning)
- PYTORCH
- scikit learn
## Minería de datos y de textos  
- Flask (servidor Web)
- Scrapy
- BeatifulSoup (Web Scraping)
