<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/0040_numpy2_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy [2] Funciones sobre matrices

In [1]:
import numpy as np                # importamos la librería NumPy como np

m = np.arange(15).reshape(3, 5)   # creamos una matriz 2D
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### shape
Proporciona el número de filas × columnas.

In [2]:
m.shape

(3, 5)

### ndim
Proporciona la dimensión de la matriz (número de ejes).

In [3]:
m.ndim

2

### size
Número de elementos que incluye una matriz.

In [4]:
m.size

15

### zeros
Crea una matriz de ceros.

In [5]:
matriz = np.zeros((3, 5))
matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### linspace
Genera una matriz con números secuenciales entre uno inicial y uno final, indicando la cantidad de números deseada.  
* Inicio en 10
* Final en 14
* Número de elementos 5

In [6]:
m=np.linspace(10, 14, 5)
m

array([10., 11., 12., 13., 14.])

* Inicio en 90
* Final en 20
* Número de elementos 5

In [7]:
m=np.linspace(90, 20, 5)
m

array([90. , 72.5, 55. , 37.5, 20. ])

## Matriz 3D
Una matriz de tres dimensiones requiere: hojas × filas × columnas.  A la tercera dimensión se la llama habitualmente hojas o páginas.

In [8]:
m3d = np.arange(24).reshape(2, 3, 4)
m3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Operar con arrays

In [9]:
array_pares=np.arange(0, 20, 2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Operaciones aritméticas

In [10]:
array_impares=array_pares + 1  # suma 1 a todos los elementos y lo convierte en un array de impares
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
array_impares * 10  # multiplicar

array([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190])

In [12]:
array_impares - array_pares  # restar arrays

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
#array_impares / array_pares # dividir arrays    da error ya que dividen entre cero

### Estadística

In [14]:
numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [15]:
array_primos.sum()        # suma

129

In [16]:
array_primos.mean()        # media

12.9

In [17]:
array_primos.var()        # varianza

73.28999999999999

### Ordenación de arrays

In [18]:
# Creamos la serie de Fibonacci
fibo = [0, 1]
for i in range (11):
    fibo.append(fibo[-1] + fibo[-2])
print(fibo)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]


In [19]:
# Convertimos la lista en un ndarray
fibonacci = np.array(fibo)
fibonacci

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

#### Desordenamos

In [20]:
# desordenamos el array
np.random.shuffle(fibonacci)   # permite desordenar un array
fibonacci

array([  1, 144,   3,  34,  89,  13,  21,  55,   1,   8,   0,   2,   5])

#### Ordenamos

In [21]:
# ordenar un array
np.sort(fibonacci)          # ordena el vector, pero no queda asignado al array fibonacci

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [22]:
fibonacci # comprobamos que no queda asignado el vector ordenado a la variable fibonacci

array([  1, 144,   3,  34,  89,  13,  21,  55,   1,   8,   0,   2,   5])

In [23]:
ordenado = np.sort(fibonacci)   # asignamos el array a la variable ordenado
ordenado

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

#### Reverso

In [24]:
inverso=ordenado[::-1]
inverso

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [25]:
inverso.sort() # si ordenamos el array inverso quedará ordenado de menor a mayor
inverso

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [26]:
inverso == np.array(fibo)     # una comprobación

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])