<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/0050_numpy3_copiar_lista.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy [3] Copia de una lista en Numpy

## Copia de una lista normal  
Las listas x e y ocupan el mismo espacio en memoria, en realidad son la misma lista  
Si añadimos un elemento con append a la lista x, quedará también añadido a la lista y

In [1]:
x = [1, 2, 3, 4]
y = x
x.append(5)
y

[1, 2, 3, 4, 5]

## Copiando valores en una lista normal  
Si queremos que el efecto anterior no se produzca y que la copia de las listas sea una copia de valores  
dando lugar a listas independientes, debemos usar el siguiente método.

In [2]:
p = [1, 2, 3, 4]
q = p[:]
p.append(5)
q

[1, 2, 3, 4]

## Copiando una lista de tipo Numpy  
Si la lista es un **ndarray** la copia será independiente sin necesidad de emplear ningún truco.

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a
np.append(a, 5)
b

array([1, 2, 3, 4])

## Seleccionar elementos de una matriz  
### Seleccionar un único elemento

In [4]:
M = np.arange(10, 22).reshape(3, 4)
M

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [5]:
np.shape(M)  # proporciona la dimensión de la matriz: filas × columnas

(3, 4)

#### Seleccionar el primer elemento

In [6]:
M[0, 0]    # Método 1

10

In [7]:
M[0][0]    # Método 2      ¿Qué método prefieres?

10

**Ejercicio**  
Selecciona un elemento para que dé como resultado 21

### Seleccionar varios elementos

#### Seleccionar la fila 1

In [8]:
M[1,:]

array([14, 15, 16, 17])

#### Seleccionar la columna 0

In [9]:
M[:,0]

array([10, 14, 18])

#### Seleccionar submatrices

In [10]:
M[:,[0]]

array([[10],
       [14],
       [18]])

In [11]:
M[:,[0]].shape    # obtenemos un matriz de orden 3×1

(3, 1)

In [12]:
M[:,[0,1]]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [13]:
M[:,[0,1]].shape    # obtenemos un matriz de orden 3×2

(3, 2)

### Seleccionando elementos con un filtro de selección

#### Generando el filtro

Generamos un array de números aleatorios, los redondeamos a dos decimales  
y vemos los que son menores que 0.5

In [14]:
np.random.rand(9).round(2) < .5

array([ True,  True, False, False, False, False, False,  True,  True])

#### Mostrando los elementos seleccionados

In [15]:
edad = np.random.randint(3, 100, size=17)   # edad de 17 personas elegidas al azar entre 3 y 99 años
edad

array([11, 12,  9, 21, 74, 35, 25, 94, 96, 35,  5, 93, 69, 72, 30, 90, 23])

In [16]:
menores=edad[edad<18]
menores

array([11, 12,  9,  5])

# Algebra lineal (numpy.linalg)  
[Linear algebra (numpy.linalg)](https://numpy.org/doc/stable/reference/routines.linalg.html)

## Matriz identidad

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Producto de matrices

In [18]:
M.dot(np.eye(4))    # M por la Identidad es igual a M. Para que se puedan multiplicar deben ser congruentes

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]])

## Resolución de sistemas lineales

In [19]:
a = np.array([[1,1,1], [0,2,5], [2,5,-1]])
b = np.array([[6], [-4], [27]])
ainv = np.linalg.inv(a)

### Método 1 multiplicando por la inversa

In [20]:
x = np.dot(ainv,b)        #Producto de dos matrices
x

array([[ 5.],
       [ 3.],
       [-2.]])

### Método 2 con solve

In [21]:
x = np.linalg.solve(a,b)  #Resuelve un sistema de ecuaciones lineales
x

array([[ 5.],
       [ 3.],
       [-2.]])