<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/calisto3_0080.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy [6] Ejes
Para matrices 2D:
* axis 0 para las columnas
* axis 1 para las filas

Para matrices en una dimensión se trabaja con un vector fila:
* En este caso el eje siempre será axis 0

## Trabajando con matrices 2D

### Suma en un eje

In [ ]:
import numpy as np
m = np.array([[1,2,3], [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(m, axis=0))    # sumando columnas

[5 7 9]


In [ ]:
print(np.sum(m, axis=1))    # sumando filas

[ 6 15]


### Concatenar por ejes
Antes de concatenar preparamos las matrices m1 y m2.

In [ ]:
m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[10,20,30], [40,50,60]])
print(m1)                               # mostramos m1
print('')
print(m2)                               # mostramos m2

[[1 2 3]
 [4 5 6]]

[[10 20 30]
 [40 50 60]]


#### Concatenamos por columnas

In [ ]:
print(np.concatenate([m1, m2], axis=0))   # concatenamos por columnas

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


#### Concatenamos por filas

In [ ]:
print(np.concatenate([m1, m2], axis=1))   # concatenamos por filas

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


## Trabajando con un vector
Trabajando con una matriz de una dimensión o vector fila. El único eje que existe es el axis 0.

### Concatenar vectores
Los vectores siempre son de tipo fila.  
Se trata de concatenar dos vectores fila.

In [ ]:
m1 = np.array([1, 2, 3])
m2 = np.array([4, 5, 6])
print(np.concatenate([m1, m2]))         # sin poner lo del eje

[1 2 3 4 5 6]


In [ ]:
print(np.concatenate([m1, m2], axis=0)) # con el axis 0

[1 2 3 4 5 6]


In [ ]:
#print(np.concatenate([m1,m2], axis=1)) # ERROR: con el axis 1