<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/calisto3_0100.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy [8] Álgebra lineal

In [ ]:
import numpy as np
m = np.array([[1,2,3], [-2,0,1]])
print(m)

[[ 1  2  3]
 [-2  0  1]]


In [ ]:
b = np.array([[1], [2], [3]])
print(b)

[[1]
 [2]
 [3]]


## Transposición matricial

In [ ]:
a = np.transpose(b)           # cambiamos filas por columnas
print(a)

[[1 2 3]]


In [ ]:
np.transpose(m)

array([[ 1, -2],
       [ 2,  0],
       [ 3,  1]])

In [ ]:
print(np.transpose(a))

[[1]
 [2]
 [3]]


#### Comprobación
Es necesario usar dobles corchetes.

In [ ]:
print(np.transpose([[1, 2, 3]]))

[[1]
 [2]
 [3]]


## Resolución de sistemas lineales
$$Ax=b$$
Nuestro objetivo es calcular $x$.

$$A=
\begin{pmatrix}
1 & -3 &  2\\
5 &  6 & -1\\
4 & -1 &  3
\end{pmatrix}$$. 

$$b=
\begin{pmatrix}
-3 \\
13 \\
8 
\end{pmatrix}$$

Solución:
$$x=A^{-1}b=
\begin{pmatrix}
-2 \\
5 \\
7 
\end{pmatrix}$$


In [ ]:
A = np.array([[1,-3,2], [5,6,-1], [4,-1,3]])
print(A)

array([[ 1, -3,  2],
       [ 5,  6, -1],
       [ 4, -1,  3]])

In [ ]:
b = np.array([[-3], [13], [8]])
print(b)

[[-3]
 [13]
 [ 8]]


In [ ]:
x = np.linalg.solve(A, b)

In [ ]:
print(x)

[[-2.]
 [ 5.]
 [ 7.]]


#### Comprobación
La función allclose nos permite comprobar que los valores, aunque no sean exactamente iguales, si son muy cercanos.

In [ ]:
np.allclose(np.dot(A,x),b)

True

In [ ]:
np.dot(A, x)

array([[-3.],
       [13.],
       [ 8.]])

In [ ]:
b

array([[-3],
       [13],
       [ 8]])

In [ ]:
np.dot(A,x) - b

array([[-3.55271368e-15],
       [ 0.00000000e+00],
       [ 3.55271368e-15]])

### Otra forma de cambiar las dimensiones de un vector
En la práctica equivale a transponer el vector.

In [ ]:
c = np.array([1,2,3])
print(c)

[1 2 3]


In [ ]:
c.shape = (3, 1)
c

array([[1],
       [2],
       [3]])

In [ ]:
c.shape = (1, 3)
c

array([[1, 2, 3]])