<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/calisto3_0060.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy [4] Operar con matrices

### Acceder a un elemento por su índice

In [ ]:
import numpy as np
m = np.arange(24).reshape(4,6)
print("El elemento de índices (1,2):", m[1,2])
print(m)

El elemento de índices (1,2): 8
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### sort()
Permite ordenar un array.

In [ ]:
m = np.array([17, 2, 11, 5, 7, 19, 3])
np.sort(m)

array([ 2,  3,  5,  7, 11, 17, 19])

### power()

In [ ]:
m = np.array([2, 3, 4, 5])
print(np.array(m**2))          # cuadrados
print(np.power(m, 2))          # cuadrados usando power
print(np.power(m, 3))          # cubos

[ 4  9 16 25]
[ 4  9 16 25]
[  8  27  64 125]


### Condición lógica

In [ ]:
m = np.array([2, 3, 4, 5])
print(np.array(m > 3))  

[False False  True  True]


### Máximo y mínimo

In [ ]:
m = np.array([2, 3, 4, 5])
print(np.array(m.min()))          # mínimo
print(np.array(m.max()))          # máximo


5
2


### Concatenar arrays

In [ ]:
m1 = np.array([2, 3, 4, 5])
m2 = np.array([20, 30, 40, 50])
print(np.concatenate((m1, m2)))

[ 2  3  4  5 20 30 40 50]


### Matriz más escalar

In [ ]:
print(m1 + 10)

[[11 12]
 [13 14]]


### Suma de matrices

In [ ]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
print(m1 + m2)

[[ 6  8]
 [10 12]]


In [ ]:
print(np.add(m1, m2))   # con la función add

[[ 6  8]
 [10 12]]


### Resta de matrices

In [ ]:
print(np.subtract(m1, m2))   # con la función subtract

[[-4 -4]
 [-4 -4]]


### Multiplicar elementos de matrices
Esto no es el producto matricial.

In [ ]:
print(np.multiply(m1, m2))   # con la función multiply

[[ 5 12]
 [21 32]]


### Dividir elementos de matrices

In [ ]:
print(np.divide(m1, m2))   # con la función divide

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Producto matricial

In [ ]:
print(m1.dot(m2))          # producto matricial con dot

[[19 22]
 [43 50]]
