<a href="https://colab.research.google.com/github/financieras/pyCourse/blob/main/jupyter/calisto3/calisto3_0075.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ordenar un ndarray

In [25]:
import random
import numpy as np

# creamos una lista con 10 números aleatorios entre 1 y 10
lista = random.sample(list(range(1,11)), 10)
print(lista, "lista de Python")     # números del 1 al 10 desordenados

vector = np.array(lista)    # ndarray
print(vector, "ndarray creado con numpy")

print(np.sort(vector), "ndarray ordenado")

# truco para imprimir el ndarray ordenado en sentido inverso
print(-np.sort(-vector), "ndarray en orden inverso")

[4, 3, 7, 2, 1, 10, 5, 6, 9, 8] lista de Python
[ 4  3  7  2  1 10  5  6  9  8] ndarray creado con numpy
[ 1  2  3  4  5  6  7  8  9 10] ndarray ordenado
[10  9  8  7  6  5  4  3  2  1] ndarray en orden inverso
